// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	null "github.com/guregu/null/v5"
)

type Application struct {
	ID              int32       `json:"id"`
	JobTitle        string      `json:"jobTitle"`
	Company         string      `json:"company"`
	Location        null.String `json:"location"`
	ApplicationDate null.Time   `json:"applicationDate"`
	UserID          int32       `json:"userId"`
	Status          string      `json:"status"`
	Notes           null.String `json:"notes"`
	CreatedAt       time.Time   `json:"createdAt"`
	UpdatedAt       time.Time   `json:"updatedAt"`
}

type User struct {
	ID         int32       `json:"id"`
	Email      string      `json:"email"`
	Password   string      `json:"password"`
	GoogleID   null.String `json:"googleId"`
	LinkedInID null.String `json:"linkedInId"`
	Name       null.String `json:"name"`
	UpdatedAt  time.Time   `json:"updatedAt"`
	CreatedAt  time.Time   `json:"createdAt"`
}
